"""empty message

Revision ID: 90869e2831d1
Revises: 0d69237c2830
Create Date: 2025-08-15 02:23:00.289736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90869e2831d1'
down_revision = '0d69237c2830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint('comments_user_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('comments_user_id_key', ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
